name: Docker

on:
  push:
    branches: [ "master" ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}
  client: ./frontend
  server: ./backend
  


jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:

    - name: Check Out Repo 
      uses: actions/checkout@v2

#     - name: Login to Docker Hub
#       uses: docker/login-action@v1
#       with:
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_TOKEN }}

#     - name: Set up Docker Buildx
#       id: buildx
#       uses: docker/setup-buildx-action@v1

    - name: Build and push
      run: |
            docker-compose up
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
            echo "login success"
            docker tag app sad-02-2022-project-v5/twosouls
            docker push sad-02-2022-project-v5/twosouls:latest
            
#       id: docker_build
#       uses: docker/build-push-action@v2
#       with:
#         context: ./
#         file: ./frontend/Dockerfile
#         push: true
#         tags: ${{ secrets.DOCKER_USERNAME }}/sad-02-2022-project-v5:latest

#     - name: Image digest
#       run: echo ${{ steps.docker_build.outputs.digest }}
