# name: Docker

# on:
#   push:
#     branches: [ "master" ]

# env:
#   REGISTRY: docker.io
#   IMAGE_NAME: ${{ github.repository }}
#   client: ./frontend
#   server: ./backend
  


# jobs:
#   build:

#     runs-on: ubuntu-latest
    
#     steps:

#     - name: Check Out Repo 
#       uses: actions/checkout@v2

#     - name: Login to Docker Hub
#       uses: docker/login-action@v1
#       with:
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_TOKEN }}   
    
#     - name: Build and push backend
#       run: |
#             docker-compose build 
#             docker tag app pranavjayanayak/2souls
#             docker push pranavjayanayak/2souls:latest
name: Docker Container CI/CD
on:
  push:
    branches: [ "master" ]

jobs:
  frontend:
    runs-on: ubuntu-latest
    env:
        CLIENT: ./frontend
    steps:
    
    - name: Build and push Dockerfile for frontend
      run: |
             docker build -t app .
             docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
             docker tag app pranavjayanayak/2souls
             docker push pranavjayanayak/2souls:latest
      working-directory: ${{env.CLIENT}}    
  
