name: Docker

on:
  push:
    branches: [ "master" ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}
  client: ./frontend
  server: ./backend
  


jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:

    - name: Check Out Repo 
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./backend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/2souls:latest
        
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
      
      
      
#     - name: Build and push backend
#       run: |
#             docker-compose build 
#             docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
#             docker tag app pranavjayanayak/2souls
#             docker push pranavjayanayak/2souls:latest
#       with:
#         context: ./
#         file: ./Dockerfile
#         push: true
#         tags: ${{ secrets.DOCKER_HUB_USERNAME }}/simplewhale:latest
#       working-directory: ${{env.server}}
      
#     - name: Build and push frontend
#       run: |
#             docker build
#             docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
#             docker tag pranavjayanayak/2souls
#             docker push pranavjayanayak/2souls:latest
