name: Docker

on:
  push:
    branches: [ "master" ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}
  client: ./frontend
  server: ./backend
  


jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:

    - name: Check Out Repo 
      uses: actions/checkout@v2

    - name: Build and push backend
      run: |
            docker build
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
            docker tag pranavjayanayak/2souls
            docker push pranavjayanayak/2souls:latest
      working-directory: ${{env.server}}
      
    - name: Build and push frontend
      run: |
            docker build
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
            docker tag pranavjayanayak/2souls
            docker push pranavjayanayak/2souls:latest
      working-directory: ${{env.client}}
